Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,7 +17,7 @@ jobs:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           REPO: ${{ github.repository }}
         run: |
-          # Check if repo is already public
+          /*# Check if repo is already public
              priv=$(gh repo view "$REPO" --json isPrivate --jq '.isPrivate')
              if [ "$priv" = "true" ]; then
               echo "Making repo public..."
@@ -33,6 +33,17 @@ jobs:
             }
           else
             echo "Repository is already public."
+          fi 
+           */
+             //
+          if [ "$priv" = "true" ]; then
+             echo "Making repository public..."
+              gh repo edit --repo "$REPO" --visibility public --accept-visibility-change-consequences || {
+              echo "Error: Failed to make the repository public."
+                exit 1
+              }
+          else
+              echo "Repo is already public."
           fi
 
   deploy-pages:
